///////////////////////////////////////////////////////////
//  Bug.cs
//  Implementation of the Class Bug
//  Generated by Enterprise Architect
//  Created on:      01-Jun-2014 8:58:52 PM
//  Original author: meeka
///////////////////////////////////////////////////////////

using System;
using System.IO;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Web.Script.Serialization;


namespace BugReportForm
{

    public class Bug
    {

        public string Area;
        public string Date;
        public string Description;
        public string Email;
        public string Model;
        public string Name;
        public string Screenshot;
        public string VSMAccount;
        public string BugDirectory;

        public Bug(string Area, string Date, string Description, string Email, string Model, string Name, string VSMAccount, string BugDirectory)
        {
            this.Area = Area;
            this.Date = Date;
            this.Description = Description;
            this.Email = Email;
            this.Model = Model;
            this.Name = Name;
            this.VSMAccount = VSMAccount;
            this.BugDirectory = BugDirectory;
        }

        ~Bug()
        {

        }

        public string GenerateJSON()
        {
            string retval;
            MemoryStream temp;
            DataContractJsonSerializer serial;
            
            serial = new DataContractJsonSerializer(typeof(Bug));
            temp = new MemoryStream(); 
            serial.WriteObject(temp, (object)this);
            StreamReader reader = new StreamReader(temp);
            retval = reader.ReadToEnd();


            return retval;
        }

        public static Bug ParseJSON(string jsonString)
        {
            Bug retval;
            MemoryStream stream = new MemoryStream(Encoding.UTF8.GetBytes(jsonString));
            DataContractJsonSerializer serial;

            serial = new DataContractJsonSerializer(typeof(Bug));
            retval = (Bug) serial.ReadObject(stream);
            return retval;
        }

        public int GetBugNumber()
        {
            int retval = -1;

            Console.WriteLine(BugDirectory);

            try
            {
                string[] filenames = Directory.GetFiles(BugDirectory, "*.json");
                retval = filenames.Length;

            }
            catch (DirectoryNotFoundException)
            {
                retval = -2;
            }
           
            return retval;
        }

        public string GetBugFilename()
        {
            string retval;

            retval = GetBugNumber() + ".json";

            return retval;
        }

        public string GetScreenshotFilename()
        {
            string retval = "";

            retval = GetBugNumber() + ".jpg";

            return retval;
        }

        public void SaveBug()
        {
            string filename = GetBugFilename();
            string JSON = GenerateJSON();

            //TODO: save JSON to file

        }
    }
}